routes/web.php
<?php

use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\User\UserController as UserDashboard;
use App\Http\Controllers\Admin\AdminController as AdminDashboard;
use App\Http\Controllers\Admin\CheckoutController as AdminCheckout;
use App\Http\Controllers\Admin\DiscountController as AdminDiscount;

use Illuminate\Support\Facades\Route;

Route::get('/',[HomeController::class,'welcome'])->name('welcome');


// socialite route
Route::get('/sign-in-google',[UserController::class,'google'])->name('signin-google');
Route::get('/auth/google/callback',[userController::class,'handleProviderCallbackGoogle'])->name('user.google.callback');
Route::get('/sign-in-github',[UserController::class,'google'])->name('signin-github');
Route::get('/auth/github/callback',[userController::class,'handleProviderCallbackGithub'])->name('user.github.callback');
//

//midtrans route get buat pembayaran ewallet, yg post buat pembayaran di indomart
Route::get('payment/success',[checkoutController::class,'midtransCallback']);
Route::post('payment/success',[checkoutController::class,'midtransCallback']);


Route::middleware(['auth'])->group(function(){
    // checkout
    Route::get('/checkout/success',[CheckoutController::class,'success'])->name('checkout.success')->middleware('ensureUserRole:user');
    Route::get('/checkout/{camp:slug}',[CheckoutController::class,'create'])->name('checkout')->middleware('ensureUserRole:user');
    Route::post('/checkout/{camp}',[CheckoutController::class,'store'])->name('checkout.store')->middleware('ensureUserRole:user');

    // user dashboard
    Route::get('/dashboard',[HomeController::class,'dashboard'])->name('dashboard');

    Route::prefix('user/dashboard')->namespace('User')->name('user.')->middleware('ensureUserRole:user')->group(function(){
        Route::get('/',[UserDashboard::class,'index'])->name('dashboard');
    });

    // admin dashboard
    // penggunaan ->namespace() tidak efektif untuk penggunaan definisi pada routing
    Route::prefix('admin/dashboard')->name('admin.')->middleware('ensureUserRole:admin')->group(function(){
        Route::get('/',[AdminDashboard::class,'index'])->name('dashboard');

        Route::post('/checkout/{checkout}',[AdminCheckout::class,'update'])->name('checkout.update');

       Route::resource('discount', AdminDiscount::class);
    });

    // Route::get('dashboard/checkout/invoice/{checkout}',[CheckoutController::class,'invoice'])->name('user.checkout.invoice');

});
require __DIR__.'/auth.php';

resources/views/admin/dashboard.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-8 offset-2">
            <div class="card mt-3">
                <div class="card-header">
                    My Camps
                </div>
                <div class="card-body">
                    @include('components.alert')
                    <table class="table">
                        <thead>
                            <tr>
                                <th>User</th>
                                <th>Camp</th>
                                <th>Price</th>
                                <th>Register Data</th>
                                <th>Paid Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($checkouts as $checkout)
                                <tr>
                                    <td>{{$checkout->User->name}}</td>
                                    <td>{{$checkout->User->title}}</td>
                                    <td>
                                        <strong>
                                            Rp{{$checkout->camp->total}}k
                                            @if ($checkout->discount_id)
                                                <span class="badge badge-success">Disc {{$checkout->discount_percentage}}k</span>
                                            @endif
                                        </strong>
                                    </td>
                                    <td>{{$checkout->created_at->format('M d Y')}}</td>
                                    <td>
                                        <strong>{{$checkout->payment_status}}</strong>
                                        {{-- @if ($checkout->is_paid)
                                        <span class="badge bg-success">Paid</span>
                                        @else
                                        <span class="badge bg-warning">Waiting</span>
                                        @endif --}}
                                    </td>
                                    <td>
                                        {{-- @if (!$checkout->is_paid)
                                            <form action="{{route('admin.checkout.update',$checkout->id)}}" method="post">
                                                @csrf
                                                <button class="btn btn-primary btn-sm">set to paid</button>
                                            </form>
                                        @endif --}}

                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="3">No Camps registered</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection