routes/web.php
<?php

use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\User\UserController as UserDashboard;
use App\Http\Controllers\Admin\AdminController as AdminDashboard;
use App\Http\Controllers\Admin\CheckoutController as AdminCheckout;
use App\Http\Controllers\Admin\DiscountController as AdminDiscount;

use Illuminate\Support\Facades\Route;

Route::get('/',[HomeController::class,'welcome'])->name('welcome');


// socialite route
Route::get('/sign-in-google',[UserController::class,'google'])->name('signin-google');
Route::get('/auth/google/callback',[userController::class,'handleProviderCallbackGoogle'])->name('user.google.callback');
Route::get('/sign-in-github',[UserController::class,'google'])->name('signin-github');
Route::get('/auth/github/callback',[userController::class,'handleProviderCallbackGithub'])->name('user.github.callback');
//

//midtrans route get buat pembayaran ewallet, yg post buat pembayaran di indomart
Route::get('payment/success',[checkoutController::class,'midtransCallback']);
Route::post('payment/success',[checkoutController::class,'midtransCallback']);


Route::middleware(['auth'])->group(function(){
    // checkout
    Route::get('/checkout/success',[CheckoutController::class,'success'])->name('checkout.success')->middleware('ensureUserRole:user');
    Route::get('/checkout/{camp:slug}',[CheckoutController::class,'create'])->name('checkout')->middleware('ensureUserRole:user');
    Route::post('/checkout/{camp}',[CheckoutController::class,'store'])->name('checkout.store')->middleware('ensureUserRole:user');

    // user dashboard
    Route::get('/dashboard',[HomeController::class,'dashboard'])->name('dashboard');

    Route::prefix('user/dashboard')->namespace('User')->name('user.')->middleware('ensureUserRole:user')->group(function(){
        Route::get('/',[UserDashboard::class,'index'])->name('dashboard');
    });

    // admin dashboard
    // penggunaan ->namespace() tidak efektif untuk penggunaan definisi pada routing
    Route::prefix('admin/dashboard')->name('admin.')->middleware('ensureUserRole:admin')->group(function(){
        Route::get('/',[AdminDashboard::class,'index'])->name('dashboard');

        Route::post('/checkout/{checkout}',[AdminCheckout::class,'update'])->name('checkout.update');

       Route::resource('discount', AdminDiscount::class);
    });

    // Route::get('dashboard/checkout/invoice/{checkout}',[CheckoutController::class,'invoice'])->name('user.checkout.invoice');

});
require __DIR__.'/auth.php';

app/Models/Discount.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Discount extends Model
{
    use HasFactory,SoftDeletes;

    protected $fillable = [
        'name',
        'code',
        'description',
        'percentage',
    ];

}

app/Http/Controllers/Admin/DiscountController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Discount\Store;
use App\Http\Requests\Admin\Discount\Update;
use App\Models\Discount;
use Illuminate\Http\Request;

class DiscountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $discounts = Discount::get();
        return view('admin.discount.index',[
            "discounts" => $discounts,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.discount.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Store $request)
    {
        $discount = Discount::create($request->all());
        $request->session()->flash('success','A new discount was created');
        return redirect(route('admin.discount.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Discount  $discount
     * @return \Illuminate\Http\Response
     */
    public function show(Discount $discount)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Discount  $discount
     * @return \Illuminate\Http\Response
     */
    public function edit(Discount $discount)
    {
        return view('admin.discount.edit',[
            'discount' => $discount,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Discount  $discount
     * @return \Illuminate\Http\Response
     */
    public function update(Update $request, Discount $discount)
    {
        $discount->update($request->all());
        $request->session()->flash('success',"Discount {$discount->name} has been updated");
        return redirect(route('admin.discount.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Discount  $discount
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Discount $discount)
    {
        $discount->delete();
        $request->session()->flash('error',"Discount {$discount->name} has been deleted");
        return redirect(route('admin.discount.index'));
    }
}

resources/views/admin/discount/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-8 offset-2">
            <div class="card mt-3">
                <div class="card-header">
                   Discount
                </div>
                <div class="card-body">
                    <form action="{{route('admin.discount.store')}}" method="post">
                        @csrf
                        <div class="form-group mb-4">
                            <label for="" class="form-label">Name</label>
                            <input type="text" class="form-control {{$errors->has('name' ? 'is-invalid' : '')}}" name="name" id="name" value="{{old('name')}}" required>
                            @if ($errors->has('name'))
                            <p class="text-danger">{{$errors->first('name')}}</p>
                        @endif
                        </div>
                        <div class="form-group mb-4">
                            <label for="" class="form-label">Code</label>
                            <input type="text" class="form-control {{$errors->has('code' ? 'is-invalid' : '')}}" name="code" id="code" value="{{old('code')}}" required>
                        </div>
                        <div class="form-group mb-4">
                            <label for="" class="form-label">Description</label>
                            <textarea name="description" cols="0" rows="2" class="form-control {{$errors->has('description' ? 'is-invalid' : '')}}" >{{old('description')}}</textarea>
                        </div>
                        <div class="form-group mb-4">
                            <label for="" class="form-label">Discount Percentage</label>
                            <input type="number" class="form-control {{$errors->has('percentage' ? 'is-invalid' : '')}}" name="percentage" id="percentage" min="1" max="100" value="{{old('percentage')}}" required>
                        </div>
                        <div class="form-group mb-4">
                           <button class="btn btn-primary" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/discount/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-8 offset-2">
            <div class="card mt-3">
                <div class="card-header">
                  Update Discount {{$discount->name}}
                </div>
                <div class="card-body">
                    <form action="{{route('admin.discount.update',$discount->id)}}" method="post">
                        @csrf
                        @method('PUT')
                        <input type="hidden" name="id" value="{{$discount->id}}">
                        <div class="form-group mb-4">
                            <label for="" class="form-label">Name</label>
                            <input type="text" class="form-control {{$errors->has('name' ? 'is-invalid' : '')}}" name="name" id="name" value="{{old('name') ?: $discount->name}}" required>
                            @if ($errors->has('name'))
                            <p class="text-danger">{{$errors->first('name')}}</p>
                        @endif
                        </div>
                        <div class="form-group mb-4">
                            <label for="" class="form-label">Code</label>
                            <input type="text" class="form-control {{$errors->has('code' ? 'is-invalid' : '')}}" name="code" id="code" value="{{old('code')?: $discount->code}}" required>
                        </div>
                        <div class="form-group mb-4">
                            <label for="" class="form-label">Description</label>
                            <textarea name="description" cols="0" rows="2" class="form-control {{$errors->has('description' ? 'is-invalid' : '')}}" >{{old('description')?: $discount->description}}</textarea>
                        </div>
                        <div class="form-group mb-4">
                            <label for="" class="form-label">Discount Percentage</label>
                            <input type="number" class="form-control {{$errors->has('percentage' ? 'is-invalid' : '')}}" name="percentage" id="percentage" min="1" max="100" value="{{old('percentage')?: $discount->percentage}}" required>
                        </div>
                        <div class="form-group mb-4">
                           <button class="btn btn-primary" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/discount/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-8 offset-2">
            <div class="card mt-3">
                <div class="card-header">
                   Discount
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12 d-flex flex-row-reverse mb-3">
                            <a href="{{ route('admin.discount.create')}}" class="btn btn-primary btn-sm">Add Discount</a>
                        </div>
                    </div>
                    @include('components.alert')
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Code</th>
                                <th>Description</th>
                                <th>Percentage</th>
                                <th colspan="2">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($discounts as $discount)
                                <tr>
                                    <td>{{$discount->name}}</td>
                                    <td>
                                        <span class="badge bg-primary">{{$discount->code}}</span>
                                    </td>
                                    <td>{{$discount->description}}k</td>
                                    <td>{{$discount->percentage}}%</td>
                                    <td>
                                      <a href="{{route('admin.discount.edit', $discount->id)}}" class="btn btn-warning">Edit</a>
                                    </td>
                                    <td>
                                        <form action="{{route('admin.discount.destroy', $discount->id)}}" method="POST">
                                            @csrf
                                            @method('delete')
                                            <button class="btn btn-danger btn-sm">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="6">No Camps registered</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection